feat: add exit option

diff --git a/src/bs b/src/bs
--- a/src/bs
+++ b/src/bs
@@ -8,11 +8,21 @@ COLUMNS=12
 # List local branches.
 IFS=$'\n' read -r -d '' -a BRANCHES < <( git branch && printf '\0' )
 
+# Add exit option.
+EXIT=EXIT
+BRANCHES+=("$EXIT")
+
 # Prompt the user to select one of the available branches.
 echo "Select branch:"
 select SELECTED_BRANCH in "${BRANCHES[@]}"; do
-  [[ -n $SELECTED_BRANCH ]] || { echo "Invalid branch! Try again." >&2; continue; }
-  break
+
+    if [ "$SELECTED_BRANCH" = "$EXIT" ]; then
+        exit
+    fi
+
+    [[ -n $SELECTED_BRANCH ]] || { echo "Invalid branch! Try again." >&2; continue; }
+    break
+
 done
 
 # Remove selection mark (*).
